data = [
    {'site_name': 'Euractiv', 'url': 'http://www.euractiv.com/', 'bias_rating': '-17', 'factual_reporting_rating': 'MIXED'},
    {'site_name': 'The Baxter Bulletin', 'url': 'https://www.baxterbulletin.com', 'bias_rating': '-2', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'CBC News (Canadian Broadcasting)', 'url': 'http://www.cbc.ca/news', 'bias_rating': '-12', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Beliefnet', 'url': 'http://www.beliefnet.com', 'bias_rating': '21', 'factual_reporting_rating': 'MIXED'},
    {'site_name': 'Splinter', 'url': 'https://splinternews.com', 'bias_rating': '-27', 'factual_reporting_rating': 'MIXED'},
    {'site_name': 'China Daily', 'url': 'http://www.chinadaily.com.cn/', 'bias_rating': '-4', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Freakonomics Radio', 'url': 'http://freakonomics.com/', 'bias_rating': '-10', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'US Uncut', 'url': 'http://usuncut.com/', 'bias_rating': '-33', 'factual_reporting_rating': 'MIXED'},
    {'site_name': 'The Next Web', 'url': 'https://thenextweb.com', 'bias_rating': '-9', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Investigative Reporters and Editors', 'url': 'https://www.ire.org/', 'bias_rating': '-1', 'factual_reporting_rating': 'VERY HIGH'},
    {'site_name': 'Socialist Standard', 'url': 'http://www.worldsocialism.org/spgb/', 'bias_rating': '-24', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'The Hindu Business Line', 'url': 'http://www.thehindubusinessline.com/', 'bias_rating': '7', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Transparency International', 'url': 'https://www.transparency.org/', 'bias_rating': '-1', 'factual_reporting_rating': 'VERY HIGH'},
    {'site_name': 'Truth Against the Machine', 'url': 'https://truthagainstthemachine.com', 'bias_rating': '-27', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'The Daily Wire', 'url': 'http://www.dailywire.com/', 'bias_rating': '29', 'factual_reporting_rating': 'MIXED'},
    {'site_name': 'The Bureau of Investigative Journalism', 'url': 'https://www.thebureauinvestigates.com/', 'bias_rating': '-4', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Big Government News', 'url': 'http://biggovernment.news/index.html', 'bias_rating': '28', 'factual_reporting_rating': 'MIXED'},
    {'site_name': 'Far Left Watch', 'url': 'https://farleftwatch.com', 'bias_rating': '29', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Black Agenda Report', 'url': 'http://blackagendareport.com/', 'bias_rating': '-22', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Vote', 'url': 'http://vote.us.org/', 'bias_rating': '-21', 'factual_reporting_rating': 'MIXED'},
    {'site_name': 'Full Fact (UK)', 'url': 'https://fullfact.org/', 'bias_rating': '-5', 'factual_reporting_rating': 'VERY HIGH'},
    {'site_name': 'Gears of Biz', 'url': 'http://gearsofbiz.com/', 'bias_rating': '-4', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Texas Tribune', 'url': 'https://www.texastribune.org/', 'bias_rating': '-2', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Weekly Standard', 'url': 'http://www.weeklystandard.com/', 'bias_rating': '23', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Public Radio International (PRI)', 'url': 'http://www.pri.org/', 'bias_rating': '-13', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Polygraph.info', 'url': 'http://www.polygraph.info/', 'bias_rating': '-2', 'factual_reporting_rating': 'VERY HIGH'},
    {'site_name': 'Winston-Salem Journal', 'url': 'http://www.journalnow.com/', 'bias_rating': '10', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Sinclair Broadcast Group', 'url': 'http://sbgi.net/', 'bias_rating': '23', 'factual_reporting_rating': 'MIXED'},
    {'site_name': 'Institute for Policy Studies', 'url': 'http://www.ips-dc.org', 'bias_rating': '-28', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Consortium News', 'url': 'https://consortiumnews.com/', 'bias_rating': '-5', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Montreal Gazette', 'url': 'http://montrealgazette.com/', 'bias_rating': '-12', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'CBS News', 'url': 'http://www.cbsnews.com/', 'bias_rating': '-12', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'International Business Times', 'url': 'http://www.ibtimes.com/', 'bias_rating': '-11', 'factual_reporting_rating': 'MIXED'},
    {'site_name': 'Government Accountability Institute', 'url': 'http://www.g-a-i.org/', 'bias_rating': '29', 'factual_reporting_rating': 'MIXED'},
    {'site_name': 'Mother Nature Network', 'url': 'https://www.mnn.com', 'bias_rating': '-15', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Baltimore Sun', 'url': 'http://www.baltimoresun.com/', 'bias_rating': '-13', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Arizona Daily Sun', 'url': 'http://azdailysun.com', 'bias_rating': '-7', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Acting Man', 'url': 'http://www.acting-man.com/', 'bias_rating': '24', 'factual_reporting_rating': 'MIXED'},
    {'site_name': 'Humanium', 'url': 'https://www.humanium.org', 'bias_rating': '-13', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'SOFREP', 'url': 'https://sofrep.com/', 'bias_rating': '11', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Center for Advanced Defense Studies', 'url': 'http://c4ads.org/', 'bias_rating': '1', 'factual_reporting_rating': 'VERY HIGH'},
    {'site_name': 'PatriotRetort.com', 'url': 'http://patriotretort.com', 'bias_rating': '28', 'factual_reporting_rating': 'MIXED'},
    {'site_name': 'Lexington Herald Leader', 'url': 'http://www.kentucky.com/', 'bias_rating': '-10', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'The Progressive', 'url': 'http://www.progressive.org/', 'bias_rating': '-23', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'The Local (Norway)', 'url': 'http://www.thelocal.no/', 'bias_rating': '-12', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Colombia Reports', 'url': 'https://colombiareports.com', 'bias_rating': '-12', 'factual_reporting_rating': 'MIXED'},
    {'site_name': 'NewsNow (UK)', 'url': 'http://www.newsnow.co.uk/h/', 'bias_rating': '-3', 'factual_reporting_rating': 'MIXED'},
    {'site_name': 'Pluralist', 'url': 'https://www.pluralist.com', 'bias_rating': '-11', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'North99', 'url': 'https://north99.org/', 'bias_rating': '-24', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'PJ Media', 'url': 'https://pjmedia.com/', 'bias_rating': '24', 'factual_reporting_rating': 'MIXED'},
    {'site_name': 'Project Syndicate', 'url': 'https://www.project-syndicate.org/', 'bias_rating': '-2', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Defense One', 'url': 'http://www.defenseone.com/', 'bias_rating': '0', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Whatfinger', 'url': 'http://www.whatfinger.com/', 'bias_rating': '26', 'factual_reporting_rating': 'MIXED'},
    {'site_name': 'Real Clear Politics', 'url': 'http://www.realclearpolitics.com/', 'bias_rating': '9', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Kyiv Post', 'url': 'https://www.kyivpost.com/', 'bias_rating': '-15', 'factual_reporting_rating': 'MIXED'},
    {'site_name': 'The Observatory', 'url': 'https://observatory.journalism.wisc.edu/', 'bias_rating': '-3', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'ICitizen', 'url': 'https://icitizen.com', 'bias_rating': '-3', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Bismarck Tribune', 'url': 'http://bismarcktribune.com', 'bias_rating': '1', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'The Jewish Press', 'url': 'http://www.jewishpress.com/', 'bias_rating': '9', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Korea Herald', 'url': 'http://www.koreaherald.com/', 'bias_rating': '8', 'factual_reporting_rating': 'MIXED'},
    {'site_name': 'Press Progress', 'url': 'https://www.pressprogress.ca/', 'bias_rating': '-20', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Portland Press-Herald', 'url': 'http://www.pressherald.com/', 'bias_rating': '-7', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Ethics and Public Policy Center (EPPC)', 'url': 'https://eppc.org/', 'bias_rating': '15', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Independent Journal Review', 'url': 'https://ijr.com/', 'bias_rating': '26', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Every CRS Report', 'url': 'https://www.everycrsreport.com/', 'bias_rating': '0', 'factual_reporting_rating': 'VERY HIGH'},
    {'site_name': 'Crosscut.com', 'url': 'http://crosscut.com/', 'bias_rating': '-13', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Pacific Research Institute', 'url': 'http://www.pacificresearch.org/home/', 'bias_rating': '9', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Gulf News', 'url': 'http://gulfnews.com/', 'bias_rating': '10', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Liberation News', 'url': 'https://www.liberationnews.org/', 'bias_rating': '-22', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Florida Times-Union', 'url': 'http://jacksonville.com/', 'bias_rating': '10', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Bipartisan Policy Center', 'url': 'https://bipartisanpolicy.org', 'bias_rating': '9', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Statesman Journal', 'url': 'http://www.statesmanjournal.com/', 'bias_rating': '8', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Richochet', 'url': 'https://ricochet.com', 'bias_rating': '26', 'factual_reporting_rating': 'MIXED'},
    {'site_name': 'Rolling Stone', 'url': 'http://www.rollingstone.com/', 'bias_rating': '-16', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'The Providence Journal', 'url': 'http://www.providencejournal.com/', 'bias_rating': '-12', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Chicago Sun Times', 'url': 'http://chicago.suntimes.com/', 'bias_rating': '-12', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Sarasota Herald-Tribune', 'url': 'http://www.heraldtribune.com/', 'bias_rating': '-3', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Politifact', 'url': 'http://www.politifact.com/', 'bias_rating': '-4', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Washington Sources', 'url': 'http://washingtonsources.org', 'bias_rating': '-27', 'factual_reporting_rating': 'MIXED'},
    {'site_name': 'Need 2 Know', 'url': 'http://theneed2know.com/', 'bias_rating': '-5', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Newsday', 'url': 'http://www.newsday.com/', 'bias_rating': '-15', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Wichita Eagle', 'url': 'http://www.kansas.com/', 'bias_rating': '6', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'National Interest', 'url': 'http://nationalinterest.org/', 'bias_rating': '6', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'GOP.com', 'url': 'https://www.gop.com/', 'bias_rating': '24', 'factual_reporting_rating': 'MIXED'},
    {'site_name': 'Exposing the Truth', 'url': 'https://www.exposingtruth.com/', 'bias_rating': '-10', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'The American Interest', 'url': 'http://www.the-american-interest.com/', 'bias_rating': '11', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Chinook Observer', 'url': 'http://www.chinookobserver.com', 'bias_rating': '-4', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'BackChannel', 'url': 'https://backchannel.com/', 'bias_rating': '-8', 'factual_reporting_rating': 'VERY HIGH'},
    {'site_name': 'Die Hard Democrat', 'url': 'http://dieharddemocrat.com/', 'bias_rating': '-26', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Al Majalla', 'url': 'http://eng.majalla.com/', 'bias_rating': '-4', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Heartland Institute', 'url': 'https://www.heartland.org/', 'bias_rating': '29', 'factual_reporting_rating': 'MIXED'},
    {'site_name': 'Grand Rapids Press', 'url': 'http://www.mlive.com/grand-rapids/#/0', 'bias_rating': '13', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Fort Worth Star-Telegram', 'url': 'http://www.star-telegram.com/', 'bias_rating': '10', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Toronto Star', 'url': 'https://www.thestar.com/', 'bias_rating': '-17', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'Wonkette', 'url': 'http://wonkette.com/', 'bias_rating': '-26', 'factual_reporting_rating': 'MIXED'},
    {'site_name': 'FitsNews', 'url': 'https://www.fitsnews.com/', 'bias_rating': '13', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'United Press International (UPI)', 'url': 'http://www.upi.com/', 'bias_rating': '3', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'American Consequences', 'url': 'https://americanconsequences.com', 'bias_rating': '24', 'factual_reporting_rating': 'MIXED'},
    {'site_name': 'Capitol Fax', 'url': 'https://capitolfax.com', 'bias_rating': '-3', 'factual_reporting_rating': 'HIGH'},
    {'site_name': 'History News Network', 'url': 'http://historynewsnetwork.org/', 'bias_rating': '-12', 'factual_reporting_rating': 'HIGH'},
]
